/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/admin/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example example@test.com */
                        username: string;
                        /** @example example */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登入成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["adminSignin"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 登出成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/user/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 登入成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["checkLoginAuth"];
                    };
                };
                /** @description 重新登入 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["checkLoginError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/products/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getProductsAll"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: string;
                    category?: string;
                };
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getProducts"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example [賣]動物園造型衣服3 */
                            title?: string;
                            /** @example 衣服2 */
                            category?: string;
                            /** @example 100 */
                            origin_price?: number;
                            /** @example 300 */
                            price?: number;
                            /** @example 個 */
                            unit?: string;
                            /** @example Sit down please 名設計師設計 */
                            description?: string;
                            /** @example 這是內容 */
                            content?: string;
                            /** @example 1 */
                            is_enabled?: number;
                            /** @example 主圖網址 */
                            imageUrl?: string;
                            /** @example [
                             *       "圖片網址一",
                             *       "圖片網址二",
                             *       "圖片網址三",
                             *       "圖片網址四",
                             *       "圖片網址五"
                             *     ] */
                            imagesUrl?: string[];
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已建立產品 */
                            message?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example imagesUrl 格式不正確 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/product/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    /** @description 要修改的 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example [賣]動物園造型衣服3 */
                            title?: string;
                            /** @example 衣服2 */
                            category?: string;
                            /** @example 100 */
                            origin_price?: number;
                            /** @example 300 */
                            price?: number;
                            /** @example 個 */
                            unit?: string;
                            /** @example Sit down please 名設計師設計 */
                            description?: string;
                            /** @example 這是內容 */
                            content?: string;
                            /** @example 1 */
                            is_enabled?: number;
                            /** @example 主圖網址 */
                            imageUrl?: string;
                            /** @example [
                             *       "圖片網址一",
                             *       "圖片網址二",
                             *       "圖片網址三",
                             *       "圖片網址四",
                             *       "圖片網址五"
                             *     ] */
                            imagesUrl?: string[];
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已更新產品 */
                            message?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example title 屬性不得為空 */
                            message?: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example id 不存在 */
                            message?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    /** @description 要刪除的 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已刪除產品 */
                            message?: string;
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example 無此權限 */
                            message?: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example 找不到產品 */
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: string;
                };
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getOrders"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/order/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    /** @description 要修改的 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example 1523539519 */
                            create_at?: number;
                            /** @example false */
                            is_paid?: boolean;
                            /** @example 這是留言 */
                            message?: string;
                            products?: {
                                L8nBrq8Ym4ARI1Kog4t?: {
                                    /** @example L8nBrq8Ym4ARI1Kog4t */
                                    id?: string;
                                    /** @example -L8moRfPlDZZ2e-1ritQ */
                                    product_id?: string;
                                    /** @example 3 */
                                    qty?: string;
                                };
                            };
                            user?: {
                                /** @example kaohsiung */
                                address?: string;
                                /** @example test@gmail.com */
                                email?: string;
                                /** @example test */
                                name?: string;
                                /** @example 0912346768 */
                                tel?: string;
                            };
                            /** @example 2 */
                            num?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["updateOrderById"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example title 屬性不得為空 */
                            message?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    /** @description 要修改的 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["removeOrdersByOrderId"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/orders/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["removeAllOrders"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/coupon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example 超級特惠價格 */
                            title?: string;
                            /** @example 1 */
                            is_enabled?: number;
                            /** @example 80 */
                            percent?: number;
                            /** @example 1555459200 */
                            due_date?: number;
                            /** @example testCode */
                            code?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已建立產品 */
                            message?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example imagesUrl 格式不正確 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/coupon/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    /** @description 要修改的 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example 超級特惠價格2 */
                            title?: string;
                            /** @example 1 */
                            is_enabled?: number;
                            /** @example 70 */
                            percent?: number;
                            /** @example 1555459200 */
                            due_date?: number;
                            /** @example testCode */
                            code?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已更新產品 */
                            message?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example title 屬性不得為空 */
                            message?: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example id 不存在 */
                            message?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    /** @description 要刪除的 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已刪除優惠券 */
                            message?: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example 找不到優惠券 */
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    page: string;
                };
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getCoupons"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description   表單上傳<br/>  <p>請注意，僅限使用 jpg、jpeg 與 png 格式，檔案大小限制為 3MB 以下。</p>  <pre>  <code>  &lt;form action="/api/thisismycourse2/admin/upload" enctype="multipart/form-data"  method="post"&gt;<br/>  &lt;input type="file" name="file-to-upload"&gt;<br/>  &lt;input type="submit" value="Upload"&gt;<br/>  &lt;/form&gt;  </code>  </pre>   */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 上傳成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["uploadSuccess"];
                    };
                };
                /** @description 上傳失敗 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["uploadError"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: string;
                };
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getArticles"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/article/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["getArticleById"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example 新增第一篇文章2 */
                            title?: string;
                            /** @example 文章內容2 */
                            description?: string;
                            /** @example test.testtest */
                            image?: string;
                            /** @example [
                             *       "tag1"
                             *     ] */
                            tag?: string[];
                            /** @example 1234566 */
                            create_at?: number;
                            /** @example alice */
                            author?: string;
                            /** @example false */
                            isPublic?: boolean;
                            /** @example 這是內容 */
                            content?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已建立文章 */
                            message?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example title 屬性不得為空 */
                            message?: string;
                        };
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    /** @description 要刪除的 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已刪除文章 */
                            message?: string;
                        };
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example 找不到文章 */
                            message?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/admin/article": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example 新增第一篇文章 */
                            title?: string;
                            /** @example 文章內容 */
                            description?: string;
                            /** @example test.testtest */
                            image?: string;
                            /** @example [
                             *       "tag1"
                             *     ] */
                            tag?: string[];
                            /** @example 1555459220 */
                            create_at?: number;
                            /** @example alice */
                            author?: string;
                            /** @example false */
                            isPublic?: boolean;
                            /** @example 這是內容 */
                            content?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success?: boolean;
                            /** @example 已建立文章 */
                            message?: string;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example title 屬性不得為空 */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/products/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userProductsAll"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: string;
                    category?: string;
                };
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userProductsAll"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/product/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userProduct"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userGetCarts"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example -L9tH8jxVb2Ka_DYPwng */
                            product_id?: string;
                            /** @example 1 */
                            qty?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userAddCart"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/cart/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example -L9tH8jxVb2Ka_DYPwng */
                            product_id?: string;
                            /** @example 1 */
                            qty?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userUpdateCart"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userDeleteCart"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/carts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userDeleteCartAll"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/coupon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            /** @example testCode */
                            code?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userApplyCoupon"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        data: {
                            user?: {
                                /** @example test */
                                name?: string;
                                /** @example test@gmail.com */
                                email?: string;
                                /** @example 0912346768 */
                                tel?: string;
                                /** @example kaohsiung */
                                address?: string;
                            };
                            /** @example 這是留言 */
                            message?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userCheckoutOrder"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: string;
                };
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userGetOrders"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/order/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    order_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userGetOrder"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/pay/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    order_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userPayment"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: string;
                };
                header?: never;
                path: {
                    api_path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userGetArticles"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/api/{api_path}/article/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    api_path: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["userGetArticles"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        adminSignin: {
            /** @example true */
            status: boolean;
            /** @example 登入成功 */
            message: string;
            /** @example QZDQO0zht4MNp7CE2t1 */
            uid: string;
            /** @example eyJhbGciOiJSUzI1NiIsImtpZCI6InRCME0yQSJ9.... */
            token: string;
            /** @example 1630734430297 */
            expired: number;
        };
        checkLoginAuth: {
            /** @example true */
            success: boolean;
            /** @example QZDQO0zht4MNp7CE2t1 */
            uid: string;
        };
        checkLoginError: {
            /** @example false */
            success: boolean;
            /** @example 請重新登入 */
            message: string;
        };
        uploadSuccess: {
            /** @example true */
            success: boolean;
            /** @example 圖片連結(https) */
            imageUrl: string;
        };
        uploadError: {
            /** @example false */
            success: boolean;
            /** @example 檔案格式錯誤 */
            message: string;
        };
        storageErrors: {
            /** @example false */
            success: boolean;
            message: {
                /** @example LIMIT_FILE_SIZE */
                code: string;
                /** @example file-to-upload */
                field: string;
                /** @example [] */
                storageErrors: unknown[];
            };
        };
        getProductsAll: {
            /** @example true */
            success: boolean;
            products: {
                /** @example 衣服3 */
                category: string;
                /** @example 這是內容 */
                content: string;
                /** @example Sit down please 名設計師設計 */
                description: string;
                /** @example -L9tH8jxVb2Ka_DYPwng */
                id: string;
                /** @example 1 */
                is_enabled: number;
                /** @example 1 */
                num: number;
                /** @example 500 */
                origin_price: number;
                /** @example 600 */
                price: number;
                /** @example [賣]動物園造型衣服3 */
                title: string;
                /** @example 個 */
                unit: string;
                /** @example 主圖網址 */
                imageUrl: string;
                /** @example [
                 *       "圖片網址一",
                 *       "圖片網址二",
                 *       "圖片網址三",
                 *       "圖片網址四",
                 *       "圖片網址五"
                 *     ] */
                imagesUrl: string[];
            }[];
        };
        getProducts: {
            /** @example true */
            success: boolean;
            products: {
                /** @example 衣服2 */
                category: string;
                /** @example 這是內容 */
                content: string;
                /** @example Sit down please 名設計師設計 */
                description: string;
                /** @example -L9tH8jxVb2Ka_DYPwng */
                id: string;
                /** @example 1 */
                is_enabled: number;
                /** @example 100 */
                origin_price: number;
                /** @example 600 */
                price: number;
                /** @example [賣]動物園造型衣服3 */
                title: string;
                /** @example 個 */
                unit: string;
                /** @example 1 */
                num: number;
                /** @example 主圖網址 */
                imageUrl: string;
                /** @example [
                 *       "圖片網址一",
                 *       "圖片網址二",
                 *       "圖片網址三",
                 *       "圖片網址四",
                 *       "圖片網址五"
                 *     ] */
                imagesUrl: string[];
            }[];
            pagination: {
                /** @example 1 */
                total_pages: number;
                /** @example 1 */
                current_page: number;
                /** @example false */
                has_pre: boolean;
                /** @example false */
                has_next: boolean;
                /** @example  */
                category: string;
            };
            /** @example [] */
            messages: unknown[];
        };
        userProducts: {
            /** @example true */
            success: boolean;
            products: {
                "-L9tH8jxVb2Ka_DYPwng": {
                    /** @example 衣服3 */
                    category: string;
                    /** @example 這是內容 */
                    content: string;
                    /** @example Sit down please 名設計師設計 */
                    description: string;
                    /** @example -L9tH8jxVb2Ka_DYPwng */
                    id: string;
                    /** @example 1 */
                    is_enabled: number;
                    /** @example 1 */
                    num: number;
                    /** @example 500 */
                    origin_price: number;
                    /** @example 600 */
                    price: number;
                    /** @example [賣]動物園造型衣服3 */
                    title: string;
                    /** @example 個 */
                    unit: string;
                    /** @example 主圖網址 */
                    imageUrl: string;
                    /** @example [
                     *       "圖片網址一",
                     *       "圖片網址二",
                     *       "圖片網址三",
                     *       "圖片網址四",
                     *       "圖片網址五"
                     *     ] */
                    imagesUrl: string[];
                };
            };
            /** @example [] */
            messages: unknown[];
        };
        userProduct: {
            /** @example true */
            success: boolean;
            product: {
                /** @example 衣服3 */
                category: string;
                /** @example 這是內容 */
                content: string;
                /** @example Sit down please 名設計師設計 */
                description: string;
                /** @example -L9tH8jxVb2Ka_DYPwng */
                id: string;
                /** @example 主圖網址 */
                imageUrl: string;
                /** @example [
                 *       "圖片網址一",
                 *       "圖片網址二",
                 *       "圖片網址三",
                 *       "圖片網址四",
                 *       "圖片網址五"
                 *     ] */
                imagesUrl: string[];
                /** @example 1 */
                is_enabled: number;
                /** @example 1 */
                num: number;
                /** @example 100 */
                origin_price: number;
                /** @example 600 */
                price: number;
                /** @example [賣]動物園造型衣服3 */
                title: string;
                /** @example 個 */
                unit: string;
            };
        };
        userProductsAll: {
            /** @example true */
            success: boolean;
            products: {
                /** @example 衣服3 */
                category: string;
                /** @example 這是內容 */
                content: string;
                /** @example Sit down please 名設計師設計 */
                description: string;
                /** @example -L9tH8jxVb2Ka_DYPwng */
                id: string;
                /** @example 主圖網址 */
                imageUrl: string;
                /** @example [
                 *       "圖片網址一",
                 *       "圖片網址二",
                 *       "圖片網址三",
                 *       "圖片網址四",
                 *       "圖片網址五"
                 *     ] */
                imagesUrl: string[];
                /** @example 1 */
                is_enabled: number;
                /** @example 1 */
                num: number;
                /** @example 100 */
                origin_price: number;
                /** @example 600 */
                price: number;
                /** @example [賣]動物園造型衣服3 */
                title: string;
                /** @example 個 */
                unit: string;
            }[];
            /** @example [] */
            messages: unknown[];
        };
        getOrders: {
            /** @example true */
            success: boolean;
            orders: {
                /** @example 1523539519 */
                create_at: number;
                /** @example -L9u11NAE0m0SpSBUDIq */
                id: string;
                /** @example false */
                is_paid: boolean;
                /** @example 這是留言 */
                message: string;
                products: {
                    L8nBrq8Ym4ARI1Kog4t: {
                        /** @example L8nBrq8Ym4ARI1Kog4t */
                        id: string;
                        /** @example -L8moRfPlDZZ2e-1ritQ */
                        product_id: string;
                        /** @example 3 */
                        qty: string;
                    };
                };
                user: {
                    /** @example kaohsiung */
                    address: string;
                    /** @example test@gmail.com */
                    email: string;
                    /** @example test */
                    name: string;
                    /** @example 0912346768 */
                    tel: string;
                };
                /** @example 2 */
                num: number;
            }[];
            pagination: {
                /** @example 1 */
                total_pages: number;
                /** @example 1 */
                current_page: number;
                /** @example false */
                has_pre: boolean;
                /** @example false */
                has_next: boolean;
                /** @example  */
                category: string;
            };
            /** @example [] */
            messages: unknown[];
        };
        updateOrderById: {
            /** @example true */
            success: boolean;
            /** @example 已更新訂單資訊 */
            message: string;
        };
        removeOrdersByOrderId: {
            /** @example true */
            success: boolean;
            /** @example 已刪除 */
            message: string;
        };
        removeAllOrders: {
            /** @example true */
            success: boolean;
            /** @example 已刪除 */
            message: string;
        };
        getCoupons: {
            /** @example true */
            success: boolean;
            coupons: {
                /** @example 6547658 */
                due_date: number;
                /** @example 1 */
                is_enabled: number;
                /** @example 80 */
                percent: number;
                /** @example 超級特惠價格 */
                title: string;
            }[];
            pagination: {
                /** @example 1 */
                total_pages: number;
                /** @example 1 */
                current_page: number;
                /** @example false */
                has_pre: boolean;
                /** @example false */
                has_next: boolean;
                /** @example  */
                category: string;
            };
            /** @example [] */
            messages: unknown[];
        };
        userApplyCoupon: {
            /** @example true */
            success: boolean;
            /** @example 已套用優惠券:testCode */
            message: string;
            data: {
                /** @example 2160 */
                final_total: number;
            };
        };
        getArticles: {
            /** @example true */
            success: boolean;
            articles: {
                /** @example alice */
                author: string;
                /** @example 123455 */
                create_at: number;
                /** @example 123 */
                description: string;
                /** @example -MT-RbUo-e-d3RZIS_kJ */
                id: string;
                /** @example url123 */
                image: string;
                /** @example false */
                isPublic: boolean;
                /** @example [
                 *       "tag1",
                 *       "tag2"
                 *     ] */
                tag: string[];
                /** @example title1234 */
                title: string;
                /** @example 1 */
                num: number;
            }[];
            pagination: {
                /** @example 1 */
                total_pages: number;
                /** @example 1 */
                current_page: number;
                /** @example false */
                has_pre: boolean;
                /** @example false */
                has_next: boolean;
                /** @example  */
                category: string;
            };
            /** @example [] */
            messages: unknown[];
        };
        getArticleById: {
            /** @example true */
            success: boolean;
            article: {
                /** @example alice */
                author: string;
                /** @example 123455 */
                create_at: number;
                /** @example 123 */
                description: string;
                /** @example -MT-RbUo-e-d3RZIS_kJ */
                id: string;
                /** @example <p>你一現出，社這邊是是因為你真是。比較第一次開可以</p> */
                content: string;
                /** @example url123 */
                image: string;
                /** @example false */
                isPublic: boolean;
                /** @example [
                 *       "tag1",
                 *       "tag2"
                 *     ] */
                tag: string[];
                /** @example title1234 */
                title: string;
                /** @example 1 */
                num: number;
            };
        };
        userGetArticles: {
            /** @example true */
            success: boolean;
            articles: {
                /** @example 新增第一篇文章 */
                title: string;
                /** @example 文章內容 */
                description: string;
                /** @example test.testtest */
                image: string;
                /** @example [
                 *       "tag1"
                 *     ] */
                tag: string[];
                /** @example 1555459220 */
                create_at: number;
                /** @example alice */
                author: string;
                /** @example false */
                isPublic: boolean;
                /** @example 這是內容 */
                content: string;
            }[];
            pagination: {
                /** @example 1 */
                total_pages: number;
                /** @example 1 */
                current_page: number;
                /** @example false */
                has_pre: boolean;
                /** @example false */
                has_next: boolean;
                /** @example  */
                category: string;
            };
            /** @example [] */
            messages: unknown[];
        };
        userGetArticle: {
            /** @example true */
            success: boolean;
            article: {
                /** @example 新增第一篇文章 */
                title: string;
                /** @example 文章內容 */
                description: string;
                /** @example test.testtest */
                image: string;
                /** @example [
                 *       "tag1"
                 *     ] */
                tag: string[];
                /** @example <p>你一現出，社這邊是是因為你真是。比較第一次開可以</p> */
                content: string;
                /** @example 1555459220 */
                create_at: number;
                /** @example alice */
                author: string;
                /** @example false */
                isPublic: boolean;
            };
        };
        userAddCart: {
            /** @example true */
            success: boolean;
            /** @example 已加入購物車 */
            message: string;
            data: {
                /** @example -L9tH8jxVb2Ka_DYPwng */
                product_id: string;
                /** @example 1 */
                qty: number;
                /** @example -LAl5v_2MhWeh3linQxx */
                id: string;
                /** @example 600 */
                total: number;
                /** @example 600 */
                final_total: number;
                product: {
                    /** @example 衣服3 */
                    category: string;
                    /** @example 這是內容 */
                    content: string;
                    /** @example Sit down please 名設計師設計 */
                    description: string;
                    /** @example -L9tH8jxVb2Ka_DYPwng */
                    id: string;
                    /** @example 主圖網址 */
                    imageUrl: string;
                    /** @example [
                     *       "圖片網址一",
                     *       "圖片網址二",
                     *       "圖片網址三",
                     *       "圖片網址四",
                     *       "圖片網址五"
                     *     ] */
                    imagesUrl: string[];
                    /** @example 1 */
                    is_enabled: number;
                    /** @example 1 */
                    num: number;
                    /** @example 500 */
                    origin_price: number;
                    /** @example 600 */
                    price: number;
                    /** @example [賣]動物園造型衣服3 */
                    title: string;
                    /** @example 個 */
                    unit: string;
                };
            };
        };
        userGetCarts: {
            /** @example true */
            success: boolean;
            data: {
                carts: {
                    coupon: {
                        /** @example testCode */
                        code: string;
                        /** @example 6547658 */
                        due_date: number;
                        /** @example -L9uIs5EfPibJpwwTMhN */
                        id: string;
                        /** @example 1 */
                        is_enabled: number;
                        /** @example 60 */
                        percent: number;
                        /** @example 超級特惠價格 */
                        title: string;
                    };
                    /** @example 2160 */
                    final_total: number;
                    /** @example -LATwxc_bIJu-AR4AlNj */
                    id: string;
                    product: {
                        /** @example 衣服3 */
                        category: string;
                        /** @example 這是內容 */
                        content: string;
                        /** @example Sit down please 名設計師設計 */
                        description: string;
                        /** @example -L9tH8jxVb2Ka_DYPwng */
                        id: string;
                        /** @example 主圖網址 */
                        imageUrl: string;
                        /** @example [
                         *       "圖片網址一",
                         *       "圖片網址二",
                         *       "圖片網址三",
                         *       "圖片網址四",
                         *       "圖片網址五"
                         *     ] */
                        imagesUrl: string[];
                        /** @example 1 */
                        is_enabled: number;
                        /** @example 1 */
                        num: number;
                        /** @example 500 */
                        origin_price: number;
                        /** @example 600 */
                        price: number;
                        /** @example [賣]動物園造型衣服3 */
                        title: string;
                        /** @example 個 */
                        unit: string;
                    };
                    /** @example -L9tH8jxVb2Ka_DYPwng */
                    product_id: string;
                    /** @example 6 */
                    qty: number;
                    /** @example 3600 */
                    total: number;
                }[];
                /** @example 3600 */
                total: number;
                /** @example 2160 */
                final_total: number;
            };
            /** @example [] */
            messages: unknown[];
        };
        userDeleteCart: {
            /** @example true */
            success: boolean;
            /** @example 已刪除 */
            message: string;
        };
        userDeleteCartAll: {
            /** @example true */
            success: boolean;
            /** @example 已刪除 */
            message: string;
        };
        userUpdateCart: {
            /** @example true */
            success: boolean;
            /** @example 已更新購物車 */
            message: string;
            data: {
                /** @example -L9tH8jxVb2Ka_DYPwng */
                product_id: string;
                /** @example 1 */
                qty: number;
            };
        };
        userCheckoutOrder: {
            /** @example true */
            success: boolean;
            /** @example 已建立訂單 */
            message: string;
            /** @example 100 */
            total: number;
            /** @example 1523539519 */
            create_at: number;
            /** @example -L9tH8jxVb2Ka_DYPwng */
            orderId: string;
        };
        userGetOrders: {
            /** @example true */
            success: boolean;
            orders: {
                /** @example 1523539519 */
                create_at: number;
                /** @example -L9u11NAE0m0SpSBUDIq */
                id: string;
                /** @example false */
                is_paid: boolean;
                /** @example 這是留言 */
                message: string;
                products: {
                    /** @example L8nBrq8Ym4ARI1Kog4t */
                    id: string;
                    /** @example -L8moRfPlDZZ2e-1ritQ */
                    product_id: string;
                    /** @example 3 */
                    qty: string;
                }[];
                user: {
                    /** @example kaohsiung */
                    address: string;
                    /** @example test@gmail.com */
                    email: string;
                    /** @example test */
                    name: string;
                    /** @example 0912346768 */
                    tel: string;
                };
                /** @example 1 */
                num: number;
            }[];
            pagination: {
                /** @example 1 */
                total_pages: number;
                /** @example 1 */
                current_page: number;
                /** @example false */
                has_pre: boolean;
                /** @example false */
                has_next: boolean;
                /** @example  */
                category: string;
            };
            /** @example [] */
            messages: unknown[];
        };
        userGetOrder: {
            /** @example true */
            success: boolean;
            order: {
                /** @example 1728973613 */
                create_at: number;
                /** @example -O9DqubzZTdJkiRiIGuy */
                id: string;
                /** @example true */
                is_paid: boolean;
                /** @example 1qq123 */
                message: string;
                /** @example 1728973617 */
                paid_date: number;
                products: {
                    "-O9DqudLJUH3hnByf0Bg": {
                        coupon: {
                            /** @example testCode */
                            code: string;
                            /** @example 1791936000 */
                            due_date: number;
                            /** @example -O988V-FceY28NH1AldL */
                            id: string;
                            /** @example 1 */
                            is_enabled: number;
                            /** @example 1 */
                            num: number;
                            /** @example 80 */
                            percent: number;
                            /** @example 123123123 */
                            title: string;
                        };
                        /** @example 800 */
                        final_total: number;
                        /** @example -O9DqudLJUH3hnByf0Bg */
                        id: string;
                        product: {
                            /** @example 蛋糕 */
                            category: string;
                            /** @example 蜜蜂蜜蛋糕，夾層夾上酸酸甜甜的檸檬餡，清爽可口的滋味讓人口水直流！ */
                            content: string;
                            /** @example 尺寸：6寸 */
                            description: string;
                            /** @example -MoGs5oIfrsXHD8bE9po */
                            id: string;
                            /** @example https://storage.googleapis.com/vue-course-api.appspot.com/hexschoolvue/1728751588618.jpg?GoogleAccessId=firebase-adminsdk-zzty7%40vue-course-api.iam.gserviceaccount.com&Expires=1742169600&Signature=SVvWwGbQdU9VoHldyhQhXTk5bMSx74QjS%2B9jTmKj5Iwe2dwwOcmeqkdFBx4yWCD3cyq4h%2B9v5gClAEjMmRBkI%2B3%2BhrETfokOqdWqCA09nQO5sslUG8%2FNPaLKmoOVWlbyLRPLlsjSTDNQlSq456wvKCjMuZ2VrQ0KesYMexUdGRIivv%2B7ZsddkQxt2SagyxR3INqR4SiEWZzeqa8VTcPqBi2SXz%2BN9ydKyuMhyj1Zgi%2BdAN5hwKqQ4tjb0RF%2BxNZRyMN637DSIh19wbYTRauS4jSePB4ZasWFy6h7ghO3LyCR1JFkUPg32cgnhVV5KUBDpzEY51jOCqzqxIq2mynjhQ%3D%3D */
                            imageUrl: string;
                            /** @example 1 */
                            is_enabled: number;
                            /** @example 2 */
                            num: number;
                            /** @example 1500 */
                            origin_price: number;
                            /** @example 1000 */
                            price: number;
                            /** @example 蜂蜜檸檬蛋糕 */
                            title: string;
                            /** @example 個 */
                            unit: string;
                        };
                        /** @example -MoGs5oIfrsXHD8bE9po */
                        product_id: string;
                        /** @example 1 */
                        qty: number;
                        /** @example 1000 */
                        total: number;
                    };
                };
                /** @example 4384 */
                total: number;
                user: {
                    /** @example 123123 */
                    address: string;
                    /** @example 123@gmail.com */
                    email: string;
                    /** @example 123123 */
                    name: string;
                    /** @example 123123123 */
                    tel: string;
                };
            };
        };
        userPayment: {
            /** @example true */
            success: boolean;
            /** @example 付款完成 */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
